techmatters/webchat

chat.html
Adds an additional option to the set.
=> Add Palo Alto Testing option

chat-staging.html
Adds staging-specific webchat file to repo.  Deployed to different CDN.
=> Add staging webchat

chat-staging.html
Jira: https://bugs.benetech.org/browse/CHI-61
- Changed the message sent to the chat when counselor leaves the conversation.
=> Goodbye message changed

chat.html
Jira: https://bugs.benetech.org/browse/CHI-61
=> Replicating changes in staging (changed goodbye message)

chat.html
Replicating https://github.com/tech-matters/webchat/pull/12 for production webchat.
No review needed.
=> Changes spelling of counselor to counsellor for production

zambia-chat-staging.html
Added `zambia-chat-staging` file with small changes on the pre engagemenet survey (removed dropdown, added non required name input).
=> Added webchat for zambia staging

configurations/beta.ts, configurations/dev.ts, configurations/index.ts, configurations/types.ts, configurations/zm-prod.ts, configurations/zm-staging.ts, global.d.ts, package-lock.json, package.json, src/aselo-webchat.ts, src/ip-tracker.ts, tsconfig.json, utils.d.ts, utils.js, webpack.config.js
Jira: https://bugs.benetech.org/browse/CHI-535
This PR enables Webchat to build for the following environments:
- dev
- beta
- zm-staging
- zm-production
Also, it makes it easy to add another environment.
=> Webchat Customization

src/aselo-webchat.ts, src/dom-utils.ts
Jira: https://bugs.benetech.org/browse/CHI-541
Primary Reviewer: @andvirga 
This PR let the client set a z-index value that will be applied to our Webchat widget.
=> Fix z-index issues

configurations/index.ts, configurations/za-prod.ts, configurations/za-staging.ts, package.json, utils.js
Jira: https://bugs.benetech.org/browse/CHI-538
This PR asks the guest's name before-hand to be used instead of **Anonymous**, for South Africa.
=> Setup Zambia staging and prod

.github/workflows/aselo_development.yml
Workflow to build and release the new version of the Webchat. Steps:
1. Checkout the repository and set NodeJS version.
2. Create and fill **secret.js** in Private folder, using the IP Find API Key saved in the repository secrets.
3. Install dependencies.
4. Build and compile Webchat.
5. Rename default bundle.js to **aselo-chat.min.js**
6. Upload the js file to S3 bucket, with the requested content type.
=> Facu chi 542

.github/workflows/aselo_beta.yml, .github/workflows/south_africa_production.yml, .github/workflows/south_africa_staging.yml, .github/workflows/zambia_production.yml, .github/workflows/zambia_staging.yml
Added workflows for all environments and corrected the name for the Upload task.
=> Added workflows for all environments

configurations/zm-staging.ts
Jira: https://bugs.benetech.org/browse/CHI-560
Primary reviewer: @andvirga 
Change welcome message for zambia.
=> Change Zambia Welcome Message

configurations/beta.ts, configurations/dev.ts, configurations/types.ts, configurations/za-prod.ts, configurations/za-staging.ts, configurations/zm-prod.ts, configurations/zm-staging.ts, src/aselo-webchat.ts, src/ip-tracker.ts
Jira: https://bugs.benetech.org/browse/CHI-592
Primary reviewer: @andvirga
This PR:
- Transform **initWebchat** into an **async** method
- Sends the **IP** over to **Aselo**
=> Send IP to Aselo

.github/workflows/test_staging.yml
Team,
We need to merge this into master for the new "Staging Test" action to work,
Thanks.
=> Staging Test Webchat

configurations/beta.ts, configurations/dev.ts, configurations/za-staging.ts, configurations/zm-staging.ts, src/aselo-webchat.ts
Jira: https://bugs.benetech.org/browse/CHI-631
This PR sends the IP with the first message.
P.S.: I've noticed some translations don't have `AutoFirstMessage` set, which means it's currently sending `undefined` as the first message.
=> Send IP on first message

.github/workflows/ethiopia_staging.yml, .github/workflows/malawi_staging.yml, configurations/et-staging.ts, configurations/index.ts, configurations/mw-staging.ts, package-lock.json, package.json, utils.js
Jira: https://bugs.benetech.org/browse/CHI-695
Primary reviewer @GPaoloni 
This PR sets up Ethiopia and Malawi Staging Webchat.
It also includes @nickhurlburt's [PR](https://github.com/techmatters/webchat/pull/44) that upgrades `@twilio/flex-webchat-ui` to fix a vulnerability issue.
=> Ethiopia and Malawi Staging Webchat

.github/workflows/ethiopia_production.yml, .github/workflows/malawi_production.yml, configurations/et-prod.ts, configurations/index.ts, configurations/mw-prod.ts, package.json, utils.js
@nickhurlburt @GPaoloni This PR sets up ET and MW production webchat.
I'll be merging it and deploying, because we may need it while I'm out.
You can always take a look at the PR, even if it's merged.
=> Setup ET and MW Prod

.github/workflows/aselo_development.yml
Jira: https://bugs.benetech.org/browse/CHI-730
This PR updates deploy action to send a Slack message after a deployment.
=> Implemented slack messaging after a deployment (development)

.github/workflows/jamaica_staging.yml, configurations/index.ts, configurations/jm-staging.ts, package.json
This PR adds a config file for jm staging. The configuration mimics the simpler ones (like et).
=> Added jm staging config

.github/workflows/jamaica_staging.yml, configurations/index.ts, configurations/jm-staging.ts, package.json, utils.js
This PR adds a config file for jm staging. The configuration mimics the simpler ones (like et). This PR is a reopen of https://github.com/techmatters/webchat/pull/58 (in [revert PR](https://github.com/techmatters/webchat/pull/59) is mentioned the reason).
=> Gian add jm staging

.github/workflows/jamaica_production.yml, configurations/index.ts, configurations/jm-prod.ts, package.json
* Config for SafeSpot Production
* Workflow for SafeSpot Production
* Updated index fil to load new config
* Extra NPM task for use in the new Workflow
- [ X ] Corresponding issue has been opened
- [ N/A ] New tests added
- [ N/A ] Strings are localized
CHI-997
1. Deploy Webchat for Jamaica Production
2. Test it using the HTML container deployed in the SafeSpot Production chat bucket: https://tl-public-chat-jm-prod.s3.us-east-1.amazonaws.com/jm-chat-prod.html
=> CHI-997: Config and workflow for SafeSpot production

package.json
=> Chi 997 safespot prod

utils.js
Another tweak for SafeSpot Prod
=> Fix utils.js

.github/workflows/canada_staging.yml, configurations/ca-staging.ts, configurations/index.ts, package.json, utils.js
Webchat for Kids Safe Phone (Canada) Staging
- [ X ] Corresponding issue has been opened
- [ N/A ] New tests added
- [ N/A ] Strings are localized
CHI-1016
* Once HTML chat container and Flex are deployed to KHP staging, deploy webchat using the workflow and run through a test webchat task
=> CHI-1016: Kids Help Phone (Canada) Staging

.github/workflows/aselo_beta.yml, .github/workflows/aselo_development.yml, .github/workflows/canada_staging.yml, .github/workflows/ethiopia_production.yml, .github/workflows/ethiopia_staging.yml, .github/workflows/jamaica_production.yml, .github/workflows/jamaica_staging.yml, .github/workflows/malawi_production.yml, .github/workflows/malawi_staging.yml, .github/workflows/south_africa_production.yml, .github/workflows/south_africa_staging.yml, .github/workflows/zambia_production.yml, .github/workflows/zambia_staging.yml
* Updated web chat deployment workflows to use Node 14
- [ X ] Corresponding issue has been opened
- [ N/A ] New tests added
- [ N/A ] Strings are localized
CHI-627
Deply web chat to dev
=> CHI-627: Node 14 workflows

.github/workflows/uk_staging.yml, configurations/index.ts, configurations/uk-staging.ts, package.json, utils.js
Primary reviewer: @stephenhand 
Webchat for Revenge Porn Staging(UK) Staging
[#1088](https://bugs.benetech.org/browse/CHI-1088)
We are able to run github workflow for this staging environment which will create a webchat in S3 bucket
=> CHI1088: RP Staging configuration and workflow

configurations/uk-staging.ts
Added missing required field to uk-staging.ts config
- [ NO ] Corresponding issue has been opened
- [ NO ] New tests added
It deploys successfully
=> Added missing required field to uk-staging.ts PreEngagementConfig

configurations/index.ts
=> Fixes to chat deployment for e2e tests

.github/workflows/te_guio_colombia_staging.yml, configurations/co-staging.ts, configurations/index.ts, configurations/zm-staging.ts, package-lock.json, package.json, utils.js
- new feature
- Configure webchat for Te Guio Colombia helpline
- [N/A] Corresponding issue has been opened
Fixes # N/A
=> CHI-1188: set up webchat for Te Guio Colombia helpline

configurations/co-staging.ts
#Reviewers
@stephenhand  @Humairaa127 
Adding spanish translations for webchat CO
=> Adding CO customizations

.github/workflows/teguio_colombia_staging.yml, configurations/co-staging.ts
- New Feature: Set up for Te Guio Colombia II helpline
Fixes #87 
CHI-1188
=> CHI-1188: set up te guio colombia II helpline

configurations/co-staging.ts
Reviewer
@stephenhand 
Sorry Steve I forgot to change the language level es -> es-ES
=> Alejandro co customizations

.github/workflows/ukraine_staging.yml, configurations/index.ts, configurations/ukr-staging.ts, package.json, utils.js
Set up Ukraine Staging Webchat
=> CHI-1278: ukr-staging added

.github/workflows/ukraine_staging.yml
=> Fix ukr workflow

configurations/za-staging.ts
=> Update za-staging.ts with operating hours

.github/workflows/zimbabwe_staging.yml, configurations/index.ts, configurations/zw-staging.ts, package.json, utils.js
- New feature: Setup Childline Zimbabwe webchat
Fixes CHI-1316
=> CHI-1: setup childline zimbabwe webchat

configurations/zw-staging.ts
=> Chi 1316 childline zimbabwe staging

.github/workflows/jamaica_staging.yml
=> Fix jm staging bucket name

.github/workflows/romania_staging.yml, configurations/index.ts, configurations/ro-staging.ts, package.json, utils.js
Set up webchat for Telefonul Copilului Romania Staging account
=> CHI-1344: Romania Staging

configurations/ca-staging.ts, configurations/ukr-staging.ts
- CA pre-engagement survey updates
- Hungary chatbot translations ukr/rus
=> Customization updates

configurations/ca-staging.ts, configurations/ukr-staging.ts
Canada configuration clean up
Ukraine translation fixes
=> Configuration clean up

package-lock.json, package.json, src/aselo-webchat.tsx, src/components/Test.tsx, tsconfig.json, webpack.config.js
Primary Reviewer: @murilovmachado 
- Adds babel dependencies to transpile react components
- Defines rules in webpack config to transform with babel-loader and updated tsconfig to compile react components
- Adds `Test` component to show react component. This will be replaced in future PRs
Fixes # [1401](https://bugs.benetech.org/browse/CHI-1401)
1. Delete `node_modules` or start with a newly cloned repo
2. `npm install`
3. build and run
=> Configure web-pack to use React

.eslintrc.json, package-lock.json, package.json, src/aselo-webchat.tsx, src/components/Test.tsx, src/dom-utils.ts, src/ip-tracker.ts, src/operating-hours.ts
Primary Reviewer: @stephenhand 
- This PR adds eslint dependencies for webchat repo, script commands and sets up eslint config rules
- Subsequent modifications to codebase to fix lint errors
Fixes #....
=> Introduces ESLint to the webchat 

.github/workflows/webchat-CI.yml
Primary Reviewer: @stephenhand 
- This workflow will verify build and check linter issues on push. No changes will be deployed / uploaded to S3 bucket in this case
- I commented out the `on: push` to avoid adding a workflow to Github Actions, but it still added it 😞
=> A new Github Actions workflow to verify build and check linting

.github/workflows/teguio_colombia_production.yml, configurations/co-production.ts, configurations/co-staging.ts, configurations/index.ts, package.json, utils.js
- Edits CO staging config file (removes some invisible characters).
- Adds CO production config files.
- Adds CO production deploy workflow
=> Te Guio production setup

.github/workflows/hungary_production.yml, .github/workflows/hungary_staging.yml
=> CHI-1425: Rename workflows

.github/workflows/malta_staging.yml, configurations/index.ts, configurations/mt-staging.ts, package.json, utils.js
Add configuration file for Malta Staging Webchat
Add reference to config to utils.js and index.ts
Create workflow file 
Add build task to package.json
=> Malta Webchat Setup

src/language.ts
Fix issue with undefined language
=> CHI-1472: Quick fix

.github/workflows/malta_production.yml, configurations/index.ts, configurations/mt-prod.ts, package.json
Add malta production
#CHI-1538
=> CHI-1538 add malta production

.github/workflows/ethiopia_production.yml, .github/workflows/jamaica_production.yml, .github/workflows/malawi_production.yml, .github/workflows/south_africa_production.yml, .github/workflows/zambia_production.yml
- Updated MW,JM,SA,ZM workflows to include serverless url. 
- [n/a] Corresponding issue has been opened
Fixes #....
- Secrets have also been updated. The workflows will then be deployed to test the app and its recently added features(end chat buttons) work for the deployed helplines
=> Updated production workflows for JM,MW,ET,ZA,ZM

configurations/mt-staging.ts
Add nickname to pre-engagement form
=> Revert 164 mt pre engagement update

configurations/ca-staging.ts, configurations/cl-staging.ts
- This PR includes changes required to match the configuration in Flex.
=> PreEngagement config changes for CA and CL

configurations/ca-staging.ts, configurations/co-production.ts, configurations/co-staging.ts, configurations/hu-prod.ts, configurations/hu-staging.ts, configurations/za-prod.ts, configurations/za-staging.ts
Primary Reviewer: @murilovmachado 
* Disable opening hours restriictions on staging accounts as this hampers testing
- N/A New tests added
CHI-1610
Use a staging account webchat out of hours, it should allow you to use it
=> CHI-1610: Disable opening hours restrictions on staging accounts

configurations/mt-prod.ts
Reapply an update to malta prod's flex flow SID.
=> CHI-1633: Fix flex flow sid (again)

configurations/co-production.ts, configurations/et-production.ts, configurations/hu-production.ts, configurations/jm-production.ts, configurations/mt-production.ts, configurations/mw-production.ts, configurations/za-production.ts, configurations/zm-production.ts, package.json
- This PR updates the production configuration files to pick the from the correct relative path after `build`
=> Build fix - Change imports for prod configurations

configurations/mt-production.ts
Point to the correct sid of the flex flow in MT production configuration.
=> Fix: point to correct mt-production flex flow

configurations/ca-staging.ts
=> Adjust French translations for Canada

configurations/mt-staging.ts
Moving chatbot questions to Webchat form
Fixes #....
=> MT WebChat Form update

configurations/mt-staging.ts
- This pull request addresses an issue where the previous merge did not identify conflicts with the master branch. However, there are build errors caused by using form types that are now outdated. The PR aims to resolve these errors by updating the form types.- https://github.com/techmatters/webchat/actions/runs/4632221447
- [n/a] Corresponding issue has been opened
Fixes # https://github.com/techmatters/webchat/actions/runs/4632221447
- build passes - https://github.com/techmatters/webchat/actions/runs/4633886017
- checked that mt staging has the fields from @sinehome's PR and MT Staging widget works
=> Update MT staging config to use new pre-engagement form types

configurations/mt-staging.ts
@sinehome  I didn't catch this earlier, but I'm fixing it now
Fixes #....
=> fixing field name mistake

src/aselo-webchat.tsx, src/end-chat/CloseChatButtons.tsx, src/end-chat/EndChat.tsx, src/end-chat/QuickExit.tsx, src/end-chat/QuickExitIcon.tsx, src/end-chat/end-chat-styles.tsx, src/translations/en.ts
- Feature refactor: Refactor the quick exit and end chat buttons
Fixes CHI-1768
=> refactor the quick exit and end chat buttons

configurations/mt-staging.ts
Cherry picking MT minor updates from Master
Fixes #....
=> minor updates (#215)

configurations/as-development.ts, package-lock.json, package.json, src/pre-engagement-form/form-components/index.tsx, src/pre-engagement-form/form-components/input-text.tsx, src/pre-engagement-form/form-components/title.tsx, src/pre-engagement-form/localization.tsx, src/safe-html-parser.tsx, webpack.config.js
Enable HTML tags in descriptions/labels including hyperlinks.
Fixes https://tech-matters.atlassian.net/browse/CHI-1668
See that hyperlinks show up just fine.
=> Enable HTML tags in descriptions/labels

configurations/cl-staging.ts
cherry picking commit, adding location to CL webchat
Fixes #....
=> adding location to Chile

configurations/mt-staging.ts
cherry pick gender value update from master
Fixes #....
=> Fix mapping for Gender value (#227)

configurations/cl-staging.ts
@annaliseirby090  Testing hyperlink
Reviewers for visibility 
Fixes #....
=> Updating CL to test hyperlink

configurations/as-development.ts, src/pre-engagement-form/form-components/checkbox.tsx, src/pre-engagement-form/form-components/form-component.tsx, src/pre-engagement-form/form-components/index.tsx, src/pre-engagement-form/form-components/styles.tsx, src/pre-engagement-form/form-components/types.ts
This PR adds support to create checkbox fields at the Pre Engagement Form.
Fixes [CHI-1669](https://tech-matters.atlassian.net/browse/CHI-1669)
Check that checkbox is now supported
=> Checkbox support

configurations/cl-staging.ts
=> adding empty value for gender

.github/workflows/custom_helpline.yml, .github/workflows/webchat-CI.yml, private/secret.example.ts, src/pre-engagement-form/index.tsx, src/pre-engagement-form/recaptchaValidation.ts
=> chore: use env specific verify url

configurations/cl-staging.ts
Reviewers for visibility
Fixes #....
=> changing message to spanish

.github/workflows/canada_production.yml
Fixes typo in recaptcha url during KHP prod deployment.
=> fix: typo in webchat deploy script

configurations/ca-production.ts
=> hotfix: flexFlowSid correction

configurations/cl-staging.ts, package-lock.json, src/pre-engagement-form/index.tsx
- **Bug fix:** friendlyName attribute not being added to pre_engagement_data
For some reason, Twilio defaults the value of `friendlyName` to `Anonymous` on Webchat.  So when we try to get the customizable values from the bot's memory, as defined on PrepopulateKeys.json in Flex-plugin, `friendlyName` always returns `Anonymous`.
**Solution**
I defined a function that checks whether `friendlyName` is defined in the pre-engagement form. If it does, it overrides the `friendlyName` value on Context. With this, we can properly map the values of the pre-engagement form on Webchat to that defined in PrepopulateKeys.json.
Fixes [CHI-1934](https://tech-matters.atlassian.net/browse/CHI-1934)
- On webchat, define the data in the pre-engagement form (include `friendlyName`)
- On Flex-plugin, define the …
=> bug: fix friendlyName attribute in pre_engagement_data

src/end-chat/CloseChatButtons.tsx, src/task.ts, tests/task.test.ts
This PR is related to https://github.com/techmatters/serverless/pull/466.
This PR adds the needed support for the changes described in https://github.com/techmatters/serverless/pull/466.
See linked PR.
=> [Bug fix] Cold transfer stuck in "locked" state when user ends the chat during a transfer

configurations/mt-staging.ts
Adding terms & conditions checkbox and link on the Webchat form
=> MT Add Ts&Cs Checkbox

package-lock.json
=> Dependabot/npm and yarn/word wrap 1.2.4 pr
