chat-staging.html, chat.html
Adds a way of localizing the various strings in webchat.
A language can be mapped to a helpline via `mapHelplineLanguage` function. If the translation for a given language does exist, the webchat is translated, if not, the default language (en-US) will be used instead.
The initial lanaguage can be configured by changing `initialLanguage` constant (changes the first render language, for example, for the EntryPointTagline).
=> Localization via Twilio strings

chat-staging.html
Jira: https://bugs.benetech.org/browse/CHI-199
Hides the input field and send button until a counselor accepts the task.
Waiting for a counselor to join:
Once a counselor joined:
The task is started by sending a message from the user but hiding it from it's UI. The counselor will still be able to see it:
=> Hides input until counselor joins chat

chat-staging.html
Jira: https://bugs.benetech.org/browse/CHI-249
This PR is related to https://github.com/tech-matters/serverless/pull/22
Input is locked after chatbot survey is completed, and until a counselor joins the chat.
Note:
- There's an error being raised in the console. It happens when user is updated, so maybe it's something related to Twilio's code. Further investigation required.
=> Input locked between bot and counselor join to the channel

chat-staging.html
Update: we're actually going to hold off on attachments for now.  But it's still a good idea to upgrade.
---
This PR updates our webchat package and adds the ability to send and receive attachments ([see Twilio docs](https://www.twilio.com/docs/flex/developer/webchat/enable-attachments)).  We'll experiment with that on staging for now.  @GPaoloni please take a look.
=> Upgrade webchat to 2.6 (was: Enable attachments in webchat)

chat.html
This PR updates webchat to the current version in staging.
Changes:
- A new message is sent from webchat to trigger a new task right after chat engagement (message hidden to the caller).
- Input hidden after completing the pre-survey with the chatbot, until a counselor joins the channel.
- Caller displayed name changed to "You".
=> Replicated changes for production chat

chat-staging.html
Per https://bugs.benetech.org/browse/CHI-302: "It's currently using the US spelling and more of the helplines will use British English so we may as well change it now for the first few implementations."
This does not change any of our variables, just the strings that the user will see.  I have tried to catch everything but please point out anything I've missed.
A companion PR for flex-plugins is here: https://github.com/tech-matters/flex-plugins/pull/247
And we will also need to change two messages in the Autopilot configuration.
=> Changes spelling of counselor to counsellor

chat-staging.html
Jira: https://bugs.benetech.org/browse/CHI-314
This PR is related to
- https://github.com/tech-matters/serverless/pull/29
- https://github.com/tech-matters/flex-plugins/pull/349
This PR blanks the `MessageCanvasTrayContent` (i.e. the message above the "start another chat" button).
=> Make the "Counselor has left the chat" message consistent across all text-based channels

package-lock.json, package.json, webpack.config.js
Jira: https://bugs.benetech.org/browse/CHI-530
This PR fixes the minified file so the browser can load it just fine.
The issue was that some dependencies had non-ASCII chars, but the browser tried to read them as ASCII, so it was throwing invalid chars. The use of `webpack-utf8-bom` plugin fixes this issue.
=> Fix minified file

configurations/types.ts, configurations/za-prod.ts, configurations/za-staging.ts, src/aselo-webchat.ts
Jira: https://bugs.benetech.org/browse/CHI-510
Primary reviewer: @murilovmachado 
This PR:
- Adds `memberDisplayOptions` optional property to `Configuration` type, and makes use of it in webchat if it exists (fallback to current behavior if not provided).
- Adds `memberDisplayOptions` overrides to ZA environments.
To test this in development, just add the following to the dev configuration file (`configurations/dev.ts`):
```
...
memberDisplayOptions: {
yourDefaultName: 'You',
yourFriendlyNameOverride: false,
theirFriendlyNameOverride: false,
theirDefaultName: 'Counsellor',
}
...
```
=> Update Counselor Name in Webchat

configurations/dev.ts, configurations/zm-staging.ts, src/aselo-webchat.ts
Jira: https://bugs.benetech.org/browse/CHI-528
Translations: https://benetech.app.box.com/file/801878647572
Change Description:
- Added Translated messages for each WebChat component using [Twilio's Templated Strings](https://www.twilio.com/docs/flex/developer/webchat/localization-and-templating#list-of-templated-strings-in-webchat).
- Added a dropdown to collect the user's language selection.
How to test this PR:
1. Executre `npm run build:zm-staging`.
2. Open `build/index.html` file in a browser.
3. Open ZM Staging environment in Okta and start a conversation.
=> Webchat Localization for Zambia native languages

configurations/zm-staging.ts
Jira: [CHI-528](https://bugs.benetech.org/browse/CHI-528)
Primary reviewer: @murilovmachado
Description:
These translations are already happening in the chat window. When the counselor ends the chat, the translation for "GoodbyeMsg" is being sent in the chat window. No need to display the same information in the tray canvas. @dee-luo to confirm this.
Related to:
- [Flex-plugins](https://github.com/tech-matters/flex-plugins/pull/428)
- [serverless](https://github.com/tech-matters/serverless/pull/51)
=> Removed MessageCanvasTrayContent messages for Zambia languages

src/aselo-webchat.ts, src/dom-utils.ts, src/index.html, src/index.ts
In order to read the given **z-index** in `<script data-z-index="999" src="aselo-chat.js"></script>` we use this line of code `document.currentScript`. But, according to the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript) this can't be run as a callback or event handler (it always returns `null` in those scenarios).
To easily fix this, we can call `document.currentScript` right at the beginning of our code, before we start handling with async code.
=> Read z-index parameter before creating Twilio's WebChat

src/aselo-webchat.ts, src/dom-utils.ts, src/index.ts
Twilio's Webchat dropdowns are not the native HTML `select` components, but a custom implementation. In summary, when we open a dropdown it actually creates another `div` in the dom, that's not a child of the webchat widget. Because of that, the webchat's z-index has no effect on these dropdowns.
This PR changes the way z-indexes are applied. Now, we listen to the new elements added to the DOM, and we add a z-index to them if their id is one of the following:
- `twilio-customer-frame` (the widget's container)
- `menu-helpline` (the `div` generated for helpline dropdown)
- `menu-language` (the `div` generated for language dropdown)
In the current implementation, we have to pay attention when adding new dropdowns: we need to add their ids into`nodeIds`: an array of ids with the elements …
=> Fix language and helpline dropdowns z-index

configurations/beta.ts, configurations/za-staging.ts
On Both ZA and Beta environments the child was receiving the goodbye message twice (in the chat area and in the tray area above the Start new chat button). This PR removes the goodbye message from the tray area.
See issue below:
=> Remove goodbye message from message tray

.githooks/commit-msg, .githooks/pre-commit, .githooks/prepare-commit-msg, README.md
Jira: https://bugs.benetech.org/browse/CHI-792
Apply same changes as techmatters/flex-plugins#531.
This PR adds git-secrets pre commit hooks to prevent key leaks. The guide on how to adopt this hooks is added to the README file of the repo.
=> Adopt AWS’s pre-commit secrets checker

configurations/jm-staging.ts
This PR fixes a syntax error: a key appeared twice in an object literal (`Translations`), in the jm staging config file, causing the deployments to fail.
@dee-luo I'm merging and deploying this fix, just tagging you so you are aware.
=> Fix jm staging config file (syntax error on dup object literal key)

configurations/index.ts, configurations/ph-staging.ts
- Create ph-staging config with languages en-US and Filipino
- Add ph-staging to index
Fixes #....
=> Ph stg config 3.8.22

.github/workflows/aselo_development.yml, .github/workflows/canada_staging.yml, .github/workflows/zambia_staging.yml, configurations/dev.ts, configurations/types.ts, private/secret.example.ts, src/aselo-webchat.ts, src/operating-hours.ts
- Added  logic to call `/operatingHours` serverless function
- Added new `closedHours` and `holidayHours` PreEngagementConfig and `checkOpeHours` flag to `dev.ts` configuration
- Added `displayOperatingHours` function to enable /disable chatting leveraging the operatingHours twilio function based on each helpline flag that have a requirement for states other than 'open'(user can chat).
Fixes # [1236](https://bugs.benetech.org/browse/CHI-1236)
- First, operatingHours function has be public - check this [PR](https://github.com/techmatters/serverless/pull/268)
- In `private/secret.ts`, set SERVERLESS_URL to dev serverless url
=> Enable chatting based on Operating hours by helpline

src/operating-hours.ts
Reviewer: @GPaoloni 
- Change to `require` serverless url instead of `import` to mitigate build error in workflow
- This should fix failing helpline deploys
=> Remove import, and use 'require' for using serverless url for getOperatingHours

.github/workflows/ethiopia_staging.yml, .github/workflows/malawi_staging.yml, .github/workflows/south_africa_staging.yml, .github/workflows/zambia_staging.yml
Rename the S3 buckets that all staging accounts deploy webchat to from names ending in 'staging' to names ending in 'stg'
CHI-947
=> CHI-947: Rename staging buckets in line with the updated naming convention

configurations/cl-staging.ts
Primary reviewer
@stephenhand
Webchat for Línea Libre, the idea is to have a webchat with the following fields that the user will need to fill out before starting the chat.
Email - Input field
Age (Edad) - Input field
Gender(Género) - Select
Tasks
=> First round of configurations for Línea Libre

src/aselo-webchat.tsx, src/components/EndChatButton.tsx, src/components/Test.tsx, src/serverless-calls/endChat.ts
- Added an 'End Chat' button that will trigger the endChat serverless function and change the task assignment to wrapping, ending the conversation
- Added call to endChat serverless function
Fixes #[1402](https://bugs.benetech.org/projects/CHI/issues/CHI-1402) partially. See [PR](https://github.com/techmatters/serverless/pull/323)
- Add Aselo production serverless url to secret
- Run webchat locally while this serverless PR's version is deployed in production in Aselo Development
=> Adds End Chat Button to UI and call to endChat serverless function

src/aselo-webchat.tsx, src/components/CloseChatButtons.tsx, src/components/EndChatButton.tsx, src/components/QuickExitButton.tsx, src/serverless-calls/endChat.ts
Primary Reviewer: @GPaoloni or @stephenhand
- This PR adds `language` from config object to redux state and subsequently use this as a request parameter for endChat function 
- [serverless PR](https://github.com/techmatters/serverless/pull/348)
Fixes #1402
- Ensuring this branch in [PR](https://github.com/techmatters/serverless/pull/348) is deployed, in webchat (local or deployed dev), get to the part where 'End Chat' can be triggered. Check the Bot message
- Alternatively, `language` can be hardcoded to a different appropriate one and checking if the messages matches what is in assets
=> Send language to localize EndChatMessage for use in serverless

src/components/EndChatButton.tsx
Primary Reviewer: @acedeywin 
- Bug fix for end chat button action not getting called. 
- [n/a] Corresponding issue has been opened
Fixes - Resolves merge conflict that is missing language parameter
- End Chat button works and child receives 'you ended chat' message.
=> Bug fix: End Chat button missing language parameter

.github/workflows/aselo_beta.yml, .github/workflows/cl_linealibre_staging.yml, .github/workflows/ethiopia_staging.yml, .github/workflows/hungary_production.yml, .github/workflows/hungary_staging.yml, .github/workflows/jamaica_staging.yml, .github/workflows/malawi_staging.yml, .github/workflows/romania_staging.yml, .github/workflows/telefonzaufania_pl_staging.yml, .github/workflows/uk_staging.yml, .github/workflows/zambia_staging.yml, .github/workflows/zimbabwe_staging.yml, configurations/pl-staging.ts
Primary Reviewer: @murilovmachado 
- Update workflows for staging accounts for CL,ET, HU, JM, MW, RO, PL, UK, ZM, ZW, and Beta accounts to call respective serverless endpoints (urls have been added to actions)
TODO:
- Ensure that `EndChatMsg` is added in messages.json to respective languages in https://github.com/techmatters/serverless/tree/master/assets/translations and serverless deployed
Fixes # 1478
- Check to ensure webchat's end chat button exists and works in CL,ET, HU, JM, MW, RO, PL, UK, ZM, ZW staging accounts after deploy
- Check that End Chat button ends the chat successfully with the 'you ended chat' message
=> Add serverless urls to workflows for staging accounts

.eslintrc.json, configurations/index.ts, src/aselo-webchat.tsx
- Language was not being stored, hence defaulting to en-US. Language in redux store is set to change now.
- Eslint config that is logging for `no-shadow` turned off. 
Fixes #....
- Token is not being authorized in Aselo Dev webchat. This branch is deployed in HU staging to test
=> Bug Fix: Language and defaultLanguage will be stored in redux

.eslintrc.json, src/aselo-webchat.tsx, src/end-chat/CloseChatButtons.tsx, src/end-chat/EndChatButton.tsx, src/end-chat/QuickExitButton.tsx, src/language.ts, src/operating-hours.ts, src/translations/en.ts, src/translations/es.ts, src/translations/hu.ts, src/translations/index.ts, src/translations/ru.ts, src/translations/ukr.ts
Primary Reviewer: @GPaoloni (to review the Spanish translations as well as the code ;-) )
* Added common translations for languages & cultures so they don't need to be specified in every config
* Added translation files for webchat languages (except local Zambia languages)
* Added translation keys for close chat to UI
We still need local language translations for Zambia if those are required (that part of the UI will be in English if not)
- N/A Verified on mobile
- N/A Verified accessibility ([Accessibility - Web applications](https://docs.google.com/document/d/1VwPDyLqw7r_iISMgDZr1FdAmAqqOIIVIxQqsYA-HaHE/edit?usp=sharing))
Fixes CHI-1472
Deploy webchat to an English language site and review the Close chat / Quick exit UI
Deploy webchat to an non-english language site and review the Close …
=> CHI-1472: Close chat / quick chat translations

src/end-chat/QuickExit.tsx, src/end-chat/end-chat-styles.tsx
Primary Reviewer: @stephenhand 
- This PR adds minor change that will help quick exit and end chat buttons to fill the full width of the webchat widget (in mobile and desktop)
- [n/a] Corresponding issue has been opened
- [n/a] English strings reviewed and copyedited
- [n/a] Strings are localized
- [n/a] Verified accessibility ([Accessibility - Web applications](https://docs.google.com/document/d/1VwPDyLqw7r_iISMgDZr1FdAmAqqOIIVIxQqsYA-HaHE/edit?usp=sharing))
Fixes # 1545 - missed this in original PR
-Change `QuickExitButtonLabel` with a longer string. 
-Run app in mobile and desktop views
=> CHI1545 Quick exit and end chat buttons fill the full width of widget 

package-lock.json, package.json, src/aselo-webchat-state.ts, src/aselo-webchat.tsx, src/end-chat/CloseChatButtons.tsx, src/end-chat/EndChat.tsx, src/end-chat/QuickExit.tsx, src/end-chat/end-chat-service.ts, src/task.ts
Primary Reviewer: @murilovmachado 
* Added aselo redux state. 
* Monitor channel for taskSid attribute and add it to the redux state
* Change exit logic based on whether a task is present on the chat channel. If no task is present, just restart the engagement
* Also prevented quick exit from attempting to finish the task before there is one on the channel
* Put the 2 'Quick Exit' tasks in a `PRomise.all` for a quicker exit
- N/A New tests added
Fixes CHI-1610
* Verify quick exit clears chat & redirects to google in every engagement stage
* Verify end chat ends current chat session in chatbot & pre-engagement stages
=> CHI-1610: Fix end chat on chatbot / pre-engagement

.eslintrc.json, configurations/beta.ts, configurations/ca-staging.ts, configurations/cl-staging.ts, configurations/co-staging.ts, configurations/dev.ts, configurations/e2e-dev.ts, configurations/et-staging.ts, configurations/hu-staging.ts, configurations/jm-staging.ts, configurations/mt-staging.ts, configurations/mw-staging.ts, configurations/pl-staging.ts, configurations/ro-staging.ts, configurations/types.ts, configurations/uk-staging.ts, configurations/za-staging.ts, configurations/zm-staging.ts, configurations/zw-staging.ts, src/aselo-webchat.tsx, src/contact-identifier/index.ts
Note: This PR should be reviewed with this Flex's PR https://github.com/techmatters/flex-plugins/pull/1146
Primary reviewer: @murilovmachado
- This PR replaces `ip` with an abstracted `contactType` to support ip, email, and any other contact identifier in the future. Currently, only supports 'ip' and 'email'
`context: {
ip,
**contactType: currentConfig.contactType,**
},
`
- Introduces a new option `contactType` and updated all helpline configurations to support `contactType`. Currently, `dev` is set to 'email' for testing. Rest of the configurations are set to 'ip'
`const contactType: ContactType = 'email';`
- AutoFirstMessage updated to send contact based on `contactType` in configuration. This can be checked in flex
- [n/a] Strings are localized
Fixes …
=> Implement email as an alternative contact identifier (in addition to ip address)

src/aselo-webchat.tsx, src/mobile-optimization/full-screen.ts, src/mobile-optimization/index.ts, src/mobile-optimization/widget-expanded-listener.ts
Primary reviewer: @mmythily @GPaoloni 
This PR removes the floating button when a chat is open at full screen on a mobile device.
Old (with floating button):
New:
Fixes https://tech-matters.atlassian.net/browse/CHI-1355
Open the chat on a mobile device and see that the floating button is not visible.
It should still be visible for desktop.
=> Hide floating button on mobile when chat is open

src/end-chat/EndChat.tsx
Currently the end chat button can be burst clicked, and this causes serverless errors.
This PR prevents this by controlling when the button is enabled/disabled.
This PR does **NOT** intend to:
- Handle disable button visuals. Some options to discuss later on:
- show spinner
- show grayed button
Fixes https://tech-matters.atlassian.net/browse/CHI-1634
Burst click end chat and see that the serverless function was called just once.
=> Prevent burst click on End Chat

src/operating-hours.ts, types.ts
This PR extends support for the new response from operatingHours function (https://github.com/techmatters/serverless/pull/409), while preserving the old format (for compatability).
Note: we don't have language info before pre-engagement, so the message will always be in the configured default language.
- Start serverless locally while sitting in https://github.com/techmatters/serverless/pull/409, and expose the url via ngrok.
- Add `export const SERVERLESS_URL = <above url>;` to `private/secret.ts`.
- Confirm that the functionality is working as expected, depending on `assets/operatingInfo/aselo-dev.private.json` (serverless):
- `operatingHours -> webchat` is "always open" (`[{ "open": 0, "close": 2400 }]`) should allow to initiate a webchat conversation.
- `operatingHours -> webchat` is …
=> Added support for new response from operatingInfo

configurations/ca-staging.ts, configurations/uk-staging.ts, src/aselo-webchat.tsx, src/dom-utils.ts, src/translations/fr.ts
new feature: Web page language detection
Fixes CHI-1070
In the `index.html` file, add the `data-language` attribute within the script tag, and set a language as the value. E.g., `data-language="ukr-HU"` save and verify that the web chat is set to the correct translation.
The [Aselo Webchat Integration](https://app.box.com/notes/850639952620?s=y9qf67jmj5pfqhczgd72g58yt3uf3qxt) document was updated to reflect the changes.
=> Web page language detection

configurations/mt-staging.ts
Updating MT webchat pre-engagement fields to not default to the first value
Fixes #....
=> Mt Webchat minor updates

src/aselo-webchat.tsx, src/pre-engagement-form/index.tsx, src/pre-engagement-form/placeholder-form.tsx
Fixes `co-staging` webchat.
This PR overcomes Twilio's WebChat limitation that we need to pass  `config.preEngagementConfig` in a certain format.
Before:
After:
Fixes https://tech-matters.atlassian.net/browse/CHI-1869
Check that `co-staging` works.
=> Fix to preEngagementConfigs with zero fields

src/pre-engagement-form/state.ts
Simple fix to the blank screen after hitting End Chat.
Fixes https://tech-matters.atlassian.net/browse/CHI-1866
Hit End Chat and check that it goes back to the pre-engagement form instead of the blank screen.
=> Fix Blank Form State

configurations/mt-staging.ts
Mapping Gender selection on MT webchat pre-engagement form to the ChildInfomationTab 
Fixes #....
=> Fix mapping for Gender value

src/aselo-webchat.tsx, src/branding-overrides/index.ts, src/dom-utils.ts
- New feature: Ability to configure color and fonts
Fixes CHI-1611
Description
I implemented two data attributes - data-background-color and data-color. The ticket only specifies the data-color  attribute, which mainly handles background color. But I also considered a scenario where a helpline would want to modify the text color. Any valid color value would work. E.g, Green, #66FFFF, rgb(102, 255, 255), hsl(180, 100%, 70%).
https://app.box.com/notes/850639952620
=> add attribute to configure background and text/font/color

.github/workflows/canada_production.yml, .github/workflows/custom_helpline.yml
This adds a very hacky way to override the verify url for CA production. So that we only keep logs that contain caller IP information in CA per the PII requirements. 
The Right Way™ would involve adding a new SSM param to every helpline in TWILIO iac that contains the correct `hrm_url` and then looking it up at deploy time or adding a region definition to each helpline workflow that could be used to map to the correct url, but either of those solutions would require a lot more work than the current problem probably deserves.
=> CHI-1888 region specific recaptcha verify url for CA prod

src/aselo-webchat.tsx, src/operating-hours.ts
This PR adds support for using the `externalWebChatLanguage` when checking the operating status of the helpline, in order to display a translated message if the response is either closed or holidays.
- Go to serverless repo, and `assets/operatingInfo/aselo-dev.private.json` change to
```
"webchat": {
"1": [],
"2": [],
"3": [],
"4": [],
"5": [],
"6": [],
"7": []
}
```
to force a closed state. Make sure you have a recent version that already contains `assets/translations/fr-CA/messages.private.json` asset. 
- Locally serve a serverless instance with above change (`npm start`) and expose via `ngrok`.
- Make your local instance of webchat point to above ngrok generated url by setting `SERVERLESS_URL` in `private/secret.ts`.
- `npm start`.
- Start a new webchat and confirm the message …
=> Set language context language before checking open hours

.eslintrc.json, .github/workflows/custom_helpline.yml, .prettierrc.js, assets/test-chat.html, package-lock.json, package.json, src/aselo-webchat.tsx, src/end-chat/EndChat.tsx, src/operating-hours.ts, src/pre-engagement-form/ReCaptcha/index.tsx, src/pre-engagement-form/index.tsx, webpack.config.js
While fixing the e2eTestMode to disable office hours and refactoring it to override the configuration instead of passing new flags around, I added a test-chat.html to be deployed to all helplines assets folder so we can test any helpline. I also fixed/enabled hot reload for the webpack dev server.
Fixes #....
Run dev server locally, deploy to development and test chat there.
=> CHI-2158: disable office hours for e2e, dev hot reload

src/language.ts, src/translations/en.ts, src/translations/es.ts, src/translations/fr.ts, src/translations/hu.ts, src/translations/ru.ts, src/translations/ukr.ts
Bug fix: "Chat With Us" remains in English and does not translate regardless of the default-language tag. 
Fixes [CHI-1873](https://tech-matters.atlassian.net/browse/CHI-1873)
[CHI-1873]: https://tech-matters.atlassian.net/browse/CHI-1873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> L3 bug investigation: webchat widget title "Chat With Us" is not translated
